# Generated by Django 6.0.5 on 2026-05-08 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_destination_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
